version: '3'
services:
 db:
   image: postgres:11
   ports:
     - "5432:5432"
   volumes:
     - ./setup/init.sql:/docker-entrypoint-initdb.d/init.sql
   environment:
     - POSTGRES_PASSWORD=postgres
   healthcheck:
     test: ["CMD-SHELL", "pg_isready -U postgres"]
     interval: 5s
     timeout: 5s
     retries: 5
 approval:
   build:
      context: .
   command: python manage.py runserver 0.0.0.0:8000
   volumes:
     - ./:/app/
   ports:
     - "0.0.0.0:8000:8000"
   depends_on:
     - db
     - redis
   environment:
     - DJANGO_SETTINGS_MODULE=config.settings.local
 celery:
   build:
      context: .
   command: celery -A config worker -l info
   volumes:
     - .:/app
   depends_on:
     - db
     - redis
   environment:
     - DJANGO_SETTINGS_MODULE=config.settings.local
 redis:
   image: redis:buster
   ports:
     - "6379:6379"
