# Generated by Django 3.2 on 2021-04-09 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentalGroup',
            fields=[
                ('group_code', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Group Code')),
                ('group_name', models.CharField(max_length=300, verbose_name='Group Name')),
            ],
            options={
                'verbose_name': 'Departmental Group',
                'verbose_name_plural': 'Departmental Groups',
                'ordering': ['group_name'],
            },
        ),
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('directorate_code', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Directorate Code')),
                ('directorate_name', models.CharField(max_length=300, verbose_name='Directorate Name')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chartofaccount.departmentalgroup')),
            ],
            options={
                'verbose_name': 'Directorate',
                'verbose_name_plural': 'Directorates',
                'ordering': ['directorate_name'],
            },
        ),
        migrations.CreateModel(
            name='CostCentre',
            fields=[
                ('cost_centre_code', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Cost Centre Code')),
                ('cost_centre_name', models.CharField(max_length=300, verbose_name='Cost Centre Name')),
                ('directorate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chartofaccount.directorate')),
            ],
            options={
                'verbose_name': 'Cost Centre',
                'verbose_name_plural': 'Cost Centres',
                'ordering': ['cost_centre_name'],
            },
        ),
    ]
