# Generated by Django 3.2 on 2021-07-02 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chartofaccount', '0002_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('project_name_role_title', models.CharField(max_length=255, verbose_name='Project name/ Title of the Role')),
                ('IR35', models.CharField(choices=[('in', 'IN'), ('out', 'OUT')], max_length=50, verbose_name='IN / OUT of Scope of IR35')),
                ('new_requirement', models.BooleanField(verbose_name='New')),
                ('name_of_contractor', models.CharField(blank=True, max_length=255, null=True, verbose_name='If Nominated Worker - please provide Name of the contractor')),
                ('uk_based', models.BooleanField(default=True, verbose_name='UK based')),
                ('overseas_country', models.CharField(blank=True, max_length=255, null=True, verbose_name='if Overseas which Country')),
                ('start_date', models.DateField(verbose_name='Anticipated Start Date')),
                ('end_date', models.DateField(verbose_name='Anticipated End Date')),
                ('type_of_security_clearance', models.CharField(choices=[('BPSS', 'BPSS'), ('sc', 'SC'), ('dv', 'DV'), ('ctc', 'CTC')], max_length=50, verbose_name='Level of Security clearance required')),
                ('contractor_type', models.CharField(choices=[('generalist', 'Generalist'), ('specialist', 'Specialist')], max_length=50, verbose_name='Category of Interim')),
                ('part_b_business_case', models.TextField(verbose_name='Business Case: Please detail why the interim resource is required.')),
                ('part_b_impact', models.TextField(verbose_name='What would be the impact of not filling this requirement.')),
                ('part_b_main_reason', models.TextField(verbose_name='What are the main reasons why this role has not been filled by a substantive Civil Servant. Please detail the strategic workforce plan for this role after the assignment end date:')),
                ('job_description_submitted', models.BooleanField(default=False)),
                ('slot_codes', models.CharField(max_length=255)),
                ('cost_centre_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costcentres', to='chartofaccount.costcentre', verbose_name='Cost Centre/Team')),
                ('directorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directorates', to='chartofaccount.directorate')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='chartofaccount.departmentalgroup')),
                ('hiring_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
