# Generated by Django 3.2 on 2021-04-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='acted_on',
            field=models.BooleanField(default=False),
        ),
    ]
