# Generated by Django 3.2 on 2021-04-09 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approval_type', models.CharField(choices=[('fin_approved', 'Finance has approved'), ('hr_approved', 'HR has approved'), ('comm_approved', 'Commercial has approved')], max_length=14)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('state', django_fsm.FSMField(default='submitted', max_length=50)),
                ('project_name_title_of_role', models.CharField(max_length=255)),
                ('cost_centre_code', models.CharField(max_length=255)),
                ('name_of_chief', models.CharField(max_length=255)),
                ('email_of_chief', models.EmailField(max_length=254)),
                ('slot_codes', models.CharField(max_length=255)),
                ('commercial_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commercial_approvals', to='workflow.approval')),
                ('finance_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_approvals', to='workflow.approval')),
                ('hr_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_approvals', to='workflow.approval')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
