# Generated by Django 3.2 on 2021-04-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementsubmitstep',
            name='email_of_hiring_manager',
            field=models.EmailField(max_length=254),
            preserve_default=False,
        ),
    ]
