# Generated by Django 3.2 on 2021-07-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='workflow_name',
            field=models.CharField(choices=[('example_workflow', 'Example workflow')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
