# Generated by Django 3.2 on 2021-07-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_flow_workflow_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='started',
            field=models.DateTimeField(null=True),
        ),
    ]
