# Generated by Django 3.2 on 2021-04-08 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_requirementsubmitstep_email_of_hiring_manager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequirementFinanceStep',
            new_name='HiringManagerApprovalStep',
        ),
        migrations.DeleteModel(
            name='RequirementHiringManagerStep',
        ),
    ]
