# Generated by Django 3.2 on 2021-07-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_alter_flow_started'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskrecord',
            old_name='input',
            new_name='step_id',
        ),
        migrations.RenameField(
            model_name='taskrecord',
            old_name='output',
            new_name='target',
        ),
        migrations.AddField(
            model_name='taskrecord',
            name='task_name',
            field=models.CharField(default='foo', max_length=100),
            preserve_default=False,
        ),
    ]
