# Generated by Django 3.2 on 2021-04-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_auto_20210408_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringmanagerapprovalstep',
            name='email_of_chief',
            field=models.EmailField(max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hiringmanagerapprovalstep',
            name='name_of_chief',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
