# Generated by Django 3.2 on 2021-07-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_auto_20210701_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrecord',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
    ]
