# Generated by Django 3.2 on 2021-04-12 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_comment_acted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='workflow.requirement'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='uk_based',
            field=models.BooleanField(default=True, verbose_name='UK based'),
        ),
    ]
