# Generated by Django 3.2 on 2021-07-02 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0005_alter_taskrecord_finished_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flow',
            name='workflow_name',
            field=models.CharField(choices=[('example_workflow', 'Example workflow'), ('approval_workflow', 'Candidate approval process')], max_length=255, verbose_name='Begin workflow'),
        ),
    ]
