# Generated by Django 3.2 on 2021-07-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_flow_flow_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='flow_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
