# Generated by Django 3.2 on 2021-07-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_flow_flow_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskrecord',
            name='task_info',
        ),
        migrations.AddField(
            model_name='taskrecord',
            name='flow_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='flow',
            name='flow_info',
            field=models.JSONField(default=dict),
        ),
    ]
