# Generated by Django 3.2 on 2021-07-02 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_auto_20210702_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskrecord',
            old_name='flow_info',
            new_name='task_info',
        ),
    ]
