# Generated by Django 3.2 on 2021-07-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_rename_flow_info_taskrecord_task_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='flow_name',
            field=models.CharField(help_text='e.g. Hire a Python Developer', max_length=255, verbose_name='What task do you need to carry out?'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='workflow_name',
            field=models.CharField(choices=[('example_workflow', 'Example workflow'), ('approval_workflow', 'Candidate approval process')], max_length=255, verbose_name='Select workflow'),
        ),
    ]
